### ISSUE TITLE
Remove `prefer_alonzo_format` from JSON output?

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/cardano-multiplatform-lib#100]
This field was added to help maintain round-trip deserailization until we get proper handling of it, but now it appears inside the JSON output. We may choose to ignore this as this code will be replaced eventually anyway -- especially considering how there is no clear fix to this

**Comment by rooooooooob** [comment]
This is relevant to the regeneration. Once we have per-era structs this won't be an issue and it won't be needed, but until then we can just ignore it for JSON as a band-aid if it's that big of a deal. Here's a quick PR since it was only 1 line of code to ignore it: #102

**Comment by rooooooooob** [comment]
It's not a big deal if we keep it or remove it IMO but I am slightly in favor of ignoring it since if you're going to/from JSON it likely breaks any guarantee for preserving the format for round-tripping, and its presence could confuse people who aren't interested in that.
