### ISSUE TITLE
Release of 3.0.0 for ASMJS

### ISSUE THREAD

**Issue by francisluz** [dcSpark/cardano-multiplatform-lib#126]
Hey guys, would be possible to release the asmjs version of the new release too? We're using it.

**Comment by SebastienGllmt** [comment]
Hey, unfortunately I'm not in a location where I can publish the asmjs build. Should be able to publish it this weekend. Sorry about the wait

**Comment by francisluz** [comment]
Thanks @SebastienGllmt.

Just as context, we're developing Begin Wallet, and our dApp Connector has to run as Service Worker, ASMJS was the only solution we found.

;)

**Comment by SebastienGllmt** [comment]
published
