### ISSUE TITLE
Cleaning up generated code

### ISSUE THREAD

**Issue by rooooooooob** [dcSpark/cardano-multiplatform-lib#139]
# Context

We are refactoring away from a single rust with `wasm_bindgen` taggings directly, over to a dedicated rust crate(s) and a separate wasm bindings crate, which should vastly improve usability from rust as we don't need to conform to the limitations of `wasm_bindgen`. While this is happening we will take advantage of improvements to `cddl-codegen` to introduce CBOR encoding tracking.

Not all the code generated from `/specs/babbage/`'s CDDL files is directly usable. Some things have a very awkward generated API or had pieces removed to help with generation. These structs will need to be hand-edited.

**Comment by gostkin** [comment]
do we have any estimate how much work should be done here?
