### ISSUE TITLE
Refactor builders over to split architecture

### ISSUE THREAD

**Issue by rooooooooob** [dcSpark/cardano-multiplatform-lib#140]
# Context

We are refactoring away from a single rust with wasm_bindgen taggings directly, over to a dedicated rust crate(s) and a separate wasm bindings crate, which should vastly improve usability from rust as we don't need to conform to the limitations of wasm_bindgen. While this is happening we will take advantage of improvements to cddl-codegen to introduce CBOR encoding tracking.

We will need to refactor the builders (e.g. tx builder) over to use the new rust-native structures, and then provide a WASM binding on top of this.

**Comment by gostkin** [comment]
#197

**Comment by rooooooooob** [comment]
Completed by #197 #223 #210
