### ISSUE TITLE
TransactionOutputAmountBuilder still build when ADA is insufficient

### ISSUE THREAD

**Issue by siegfried** [dcSpark/cardano-multiplatform-lib#144]
`TransactionOutputAmountBuilder` still build when ADA is 0. `coinsPerUtxoByte` is set and `with_asset_and_min_required_coin` is called. Is this a feature or a bug?

**Comment by SebastienGllmt** [comment]
Are you saying that `with_asset_and_min_required_coin` is broken and not properly setting the ADA amount in some cases? I'm not sure what you mean by "when ADA is 0" because `with_asset_and_min_required_coin` doesn't take an ADA amount

**Comment by siegfried** [comment]
Sorry, it seems I misunderstood `with_asset_and_min_required_coin` which would override the ADA been set.
