### ISSUE TITLE
How would I do something like emurgos: add_inputs_from(inputs: TransactionUnspentOutputs, strategy: number): void with dcsparks: select_utxos(strategy: number): void

### ISSUE THREAD

**Issue by DorienP** [dcSpark/cardano-multiplatform-lib#181]
I notice the similarity with both of these methods but I wanted to know how to switch over to dcspark using this pattern?
```
   const utxos = (await Wallet.getUtxos()).map(utxo => CardanoWasm.TransactionUnspentOutput.from_bytes(Buffer.from(utxo, "hex")))
    
    const utxoOut = CardanoWasm.TransactionUnspentOutputs.new();
    utxos.map((utxo) => utxoOut.add(utxo));
    
    txBuilder.add_inputs_from(
      utxoOut,
      0
  );
```
with dcspark :
```
txBuilder.select_utxos(0)
```

**Comment by DorienP** [comment]
I notice the similarity with both of these methods but I wanted to know how to switch over to dcspark using this pattern?
```
   const utxos = (await Wallet.getUtxos()).map(utxo => CardanoWasm.TransactionUnspentOutput.from_bytes(Buffer.from(utxo, "hex")))
    
    const utxoOut = CardanoWasm.TransactionUnspentOutputs.new();
    utxos.map((utxo) => utxoOut.add(utxo));
    
    txBuilder.add_inputs_from(
      utxoOut,
      0
  );
```
with dcspark :
```
txBuilder.select_utxos(strategy)
```

**Comment by DorienP** [comment]
I think I just found the correct input: 
```
txBuilder.add_reference_input()
```
is this correct?

**Comment by SebastienGllmt** [comment]
You need to call `add_utxo` multiple times and then call `select_utxos` afterwards

> add_reference_input

this function is only used if you want to add reference inputs (a special kind of input for a Plutus functionality called reference inputs)

**Comment by DorienP** [comment]
Thank you for the response. What if there is only 1 utxo? Would that still be viable? @SebastienGllmt

**Comment by SebastienGllmt** [comment]
Yes, should work. If you have a single utxo, you don't need to do utxo selection and just add the input manually if you want

**Comment by DorienP** [comment]
Took me long enough, thank you for the explanation. We're repping your code now
https://www.npmjs.com/package/@dotare/cardano-delegation?activeTab=dependencies
