### ISSUE TITLE
why `StakeCredential` for payment credential?  

### ISSUE THREAD

**Issue by waalge** [dcSpark/cardano-multiplatform-lib#186]
I can't find any explanation as to why credential is called `StakeCredential` and not simply `Credential` 

https://github.com/dcSpark/cardano-multiplatform-lib/blob/develop/chain/rust/src/address.rs#L543

**Comment by SebastienGllmt** [comment]
The simple answer is that it's because this is what it's called in the binary specification. I agree it's not a great name though

**Comment by waalge** [comment]
What's the binary specification ? 

I only know the cddl files as the "source-of-truth", but there it has simply address.
The address is broken down only as comments where it refers to ... things suggestively named, not formally defined :-/
~~(Why is the address defined as a comment?? AFAICS cddl supports bit level specification, although given its not used I'm guessing that's why its not supported in the `cddl-codegen` tool... again afaics)~~ 

Edit: It's been pointed out to me that addresses are custom encoded and not cbor-able. And that a "technical spec" is available as part of [CIP19](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0019/CIP-0019-cardano-addresses.abnf)

**Comment by SebastienGllmt** [comment]
https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl#L203

**Comment by waalge** [comment]
The cddl files specify `stake_credential`, but they don't specify `address`.

There's no benefit of autogenerated encoding/decoding functions for address so it could have used a new `Credential` type.

**Comment by rooooooooob** [comment]
>(Why is the address defined as a comment?? AFAICS cddl supports bit level specification, although given its not used I'm guessing that's why its not supported in the cddl-codegen tool... again afaics)

CDDL supports bit-level specification (`.bits`) but it's not nearly robust enough to specify the adress format. It's more for bit-flag type specifications which would only help with the header bytes of addresses, not the entire format.

>There's no benefit of autogenerated encoding/decoding functions for address so it could have used a new Credential type.

The address format in the binary spec refers to just `keyhash28` / `scripthash28`. The `stake_credential` stuff is used in other non-address parts. The type already existed in the rest of code (`stake_registration`, `stake_deregistration`, `stake_delegation`, `move_instantaneous_reward`) so we just used that. It could be renamed (in the new CML version) if it confuses people why we have a "stake" credential used as a payment credential as well. It could, however, confuse people migrating from old CML or from CSL who are used to `StakeCredential`, but a type alias could sort that out.

>There's no benefit of autogenerated encoding/decoding functions for address so it could have used a new Credential type.

Is it worth it having two types that do basically the same thing? It could be if we end up adding utility functionality to either of them, but they're just wrappers around the hashes and I'm not sure what that would be. If we can think of anything then that would make sense. It would mean extra conversion between the two as well.

**Comment by waalge** [comment]
Thanks for the explainers. You're saying its possible, but suboptimal to define the address in cddl? I haven't got my head around this, I thought I was told that it wasn't possible - I should just try to do it and see what the issues are.  

I does make sense that since the datatypes would be equivalent, that StakeCredential is reused. If it was put to a vote, I think I would vote for an `PaymentCredential` alias.

This whole thing lead me down a rabbit hole that there is a not-insignificant amount of cardano outside the "Specs". 
I really like the approach of using the cddl-codegen to 'ensure' correctness.  It's annoying there are omissions in the spec(s) for things like address (maybe script context is a different example - not sure). 
 
Given that the leg work has already been done - there is a functioning `address.rs` module - this is surely a silly idea but. It would be satisfying if this could be done in a uniform way.
The cip19 abnf could be embedded into the cddl file (https://datatracker.ietf.org/doc/html/rfc9165)

More than satisfying, at the moment it looks like libs are autogenerated by `cddl-codegen` and then modified by hand. 
[This](https://github.com/dcSpark/cardano-multiplatform-lib/blob/develop/chain/README.md) says its autogenerated, but I don't generate the same result. 
It would be preferable to, say, manually review the "formal spec files" and then verify by replicating the  build of the library.

**Comment by rooooooooob** [comment]
>You're saying its possible, but suboptimal to define the address in cddl? 

It's not possible to get the exact format. The closest i can think of is:
```
; this is a hack since it will always have the header in the first spot and never anywhere else but with how .cborseq works this is what we can do
adderess_struct_hack = 
 header /
 credential

credential = addr_keyhash / script_hash

header = uint .size 1
; maybe do a header_bits to help using .bits to index into the byte

address = bytes .cborseq address_struct_hack
```

This is too accepting as this would accept many invalid addresses (e.g. repeating headers, lack of headers, etc - basically any bytes since repeating header could be anything) so I'm guessing this is why IOHK just went with a comment instead.

You can't put them in a struct to guarantee the format either as that would introduce array or map tags (e.g.:)
```
address_struct = [header, credential, ?credential]
address = bytes .cbor address_struct
; or for a variant
enterprise_address = [header, credential]
```
I don't think a top-level basic group is valid (to avoid the array/map tags) as a target either as they're meant for composing other types (but this would give a good struct layout). And if you want to verify the header bytes you could use constants for those but you'd end up with like 128 for payment addresses + 32 for reward addresses + 1 for byron addresses. So even without those array/map tag issue it would've just been much more explicit to just put it in a comment. 

The .`bits` on its own is only for bitflags which only concerns the header byte.

>I think I would vote for an PaymentCredential alias.

That was the approach I was first thinking about as a compromise. However, IIRC type aliases aren't applied through wasm-bindgen output. I'm not sure if there's a config for that so the alias would only show up in rust documentation I think. We could at least comment the type though.

>More than satisfying, at the moment it looks like libs are autogenerated by cddl-codegen and then modified by hand.

Yeah there's some amount of hand-editing afterwards. We're working towards minimizing/eliminating this. Expect to see a PR soon using recent changes in cddl-codegen that change the format.

**Comment by waalge** [comment]
Thanks for that in-depth response. Makes sense. I will stare at rfc9165, if for nothing but an exercise in how these things work. 

And I'll be watching this and cddl-codegen lib :eyes:

**Comment by rooooooooob** [comment]
Some possible courses of action:

1.  Status quo (+ comment)
2.  `pub type PaymentCredential = StakeCredential;`
3. Rename `StakeCredential` -> `Credential` (or whatever other name)
4. ^ rename like 3. + two aliases `PaymentCredential = Credential` + `StakeCredential = Credential`

**Comment by waalge** [comment]
I think 1. would have been sufficient to not raise this gh issue. 

4 would be more coherent. Although I think plutus had both a "StakingCredential" and "StakeCredential" or at least used both `stake` and `staking` - that was annoying
