### ISSUE TITLE
Transaction deserialization simplifies outputs to `legacy_transaction_output` when possible

### ISSUE THREAD

**Issue by sourabhxyz** [dcSpark/cardano-multiplatform-lib#201]
All the outputs in my transaction had outputs in [`post_alonzo_transaction_output`](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl#L87) format but after deserialization, outputs which could be simplified to [`legacy_transaction_output`](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl#L79) format, got simplified into it. Is this intentional? I can see it happening at wallet level (when wallet performs deserialization in `signTx` method) and this changing of transaction cbor is leading to inconsistency with what transaction hash we expect and what actually turns out to be.

**Comment by rooooooooob** [comment]
@sourabhxyz  I don't think this should happen anymore. There was some hand-coding before that did this. We now respect formats and remember all the fiddly CBOR encoding details (e.g. how many bytes used per int, definite vs indefinite arr/maps, key order, etc) correctly now. I've tested everything on mainnet and preprod (and sancho testnet) and everything seems to roundtrip the CBOR to the original.

**Comment by sourabhxyz** [comment]
@rooooooooob Understood, thank you.
