### ISSUE TITLE
Support duplicate keys before Valentine

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/cardano-multiplatform-lib#209]
The Valentine hardfork removed the ability to have duplicate keys in map types in Cardano (https://github.com/dcSpark/cddl-codegen/issues/38). Theoretically CML should support duplicate keys before Valentine (at least in key places where they actually occurred onchain on mainnet) to be fully compatible

**Comment by rooooooooob** [comment]
Do we know all the places we need to support? We need to in metadatum keys (or was it metadata labels?). Did we ever encounter it in plutus datums?

**Comment by SebastienGllmt** [comment]
I think right now in CML we have patches for duplicate keys in all the places we ran into it in practice, right?

**Comment by SebastienGllmt** [comment]
https://github.com/dcSpark/cardano-multiplatform-lib/pull/74
