### ISSUE TITLE
Network info/id functionality

### ISSUE THREAD

**Issue by rooooooooob** [dcSpark/cardano-multiplatform-lib#231]
See discussion in #222 

NetworkId is just a u32 for now which isn't quite right as it can't take on all u32 values. We might want its own struct that does validation and with named constructors for certain networks.

NetworkInfo mentions protocol magic and such and is only for legacy byron support, but users might want to be able to use it for current networks too i.e. CIP34 network registry.

At minimum we could document this better as for which networks those are.

**Comment by SebastienGllmt** [comment]
NetworkId is a u8, not u32 (perhaps you were thinking of protocol magic?). Also, there is no reason why it couldn't be any valid value. Just because no network uses as specific value now, doesn't mean it can't be used in the future

Also protocol magic is used in the handshake protocol for the network layer, so it's not just use for Byron addresses

**Comment by rooooooooob** [comment]
It's a `u32` because `u8` can't be exposed to WASM directly. That's why I said it can't take all u32 values.

**Comment by rooooooooob** [comment]
How would it work for addresses if they used a bigger value though? There are only 4 bits in it for network id.

**Comment by rooooooooob** [comment]
Actually it might only not be able to exposed to wasm_bindgen in certain situations now that I look at it, since the address code exposes the header as u8 fine. I'll have to look again to see why there was a problem with network id.

**Comment by rooooooooob** [comment]
Weird. It seems to work perfectly fine now as `u8` actually. Maybe something else that was different in the code caused the error. It was definitely getting one of the wasm_bindgen traits not being implemented for `u8` but now it's fine. It would give that if you did `&u8` but I didn't change value vs reference semantics at all in that PR.

So I guess the question is now, do we revert back to `u8` or do we make it its own type still?

If it's a raw `u8`, what do we do for addresses if it's over 4-bits?

**Comment by rooooooooob** [comment]
Closing this as we have a `NetworkId` struct now.
