### ISSUE TITLE
Missing methods TransactionUnspentOutput

### ISSUE THREAD

**Issue by solidsnakedev** [dcSpark/cardano-multiplatform-lib#338]
The `TransactionUnspentOutput` class is missing methods that allow access to the input or output, it should be similar to those in `TransactionOutput` and `TransactionInput` 
![image](https://github.com/dcSpark/cardano-multiplatform-lib/assets/57915702/829819da-8a17-4b10-9c6a-aa363a2aacb5)

```typescript
const test = TransactionUnspentOutput.from_cbor_hex("8282582095cdc0b23b21f9f0ac5b2580b025c4bc64034ff5e9d97f8ecb51d78151a3223f18228258390115c2e6ade9b92c86a252f6fb1d2a01b2d70a6a5db943fd368bd30c6fc28ad299e38676d1647f6d8f31234c34a914d8488ff86ca2d5df70df821a00116d86a1581cffbe813449ec642880ec645af88a4df2f586b0b677c44ecf4a1ef834a145414d494c4b01")
```

**Comment by rooooooooob** [comment]
@solidsnakedev added here: #341
