### ISSUE TITLE
`258` tag for sets is not being correctly serialized

### ISSUE THREAD

**Issue by SeungheonOh** [dcSpark/cardano-multiplatform-lib#364]
When serializing `set` and `nonempty_set`, current implementation of serializers does not correctly include `258` tag that will be required starting Polmin hardfork. 

I believe @solidsnakedev have working solution for this issue. This issue is for tracking purposes.

**Comment by rooooooooob** [comment]
The reason we don't serialized this way **_as the default behavior_**  is to make txs smaller, as it's not currently required.

>current implementation of serializers does not correctly include 258 tag 

It **_is_** correctly serialized for any transactions that were created using that format. It will be required later as you have mentioned, but when that happens there might be other changes to the binary spec and we want CML to properly support exactly that hardfork which would require removing `NonEmptySet` 100% from the default crate and only using it in the `cml-multi-era/src/babbage` module. We have an approach of not mixing eras and the `cml-chain` crate only supports the current era, whereas previous eras go in `cml-multi-era`.

**Comment by SeungheonOh** [comment]
I see. I agree that this is the sensible default behavior for mainnet. However, Polmin fork have arrived in preview and testnet, and since this tag is required for next hardfork I'm seeing some transactions failing. 

Perhaps we can have "prerelease" version of CML that supports new serialization format to test before hardfork arrives in mainnet?

**Comment by rooooooooob** [comment]
I checked the binary specs folder in the ledger specs and I don't see a .cddl definition yet for Polmin. If this is the only binary spec change I am fine with making the default behavior to be to serialize the tag, but we must still respect the encodings for current Conway/chang 1 transactions so that round-tripping works.

**Comment by SeungheonOh** [comment]
As far as I can tell, they will be using same conway format, but following comment states tags for set will be enforced starting next hardfork.

https://github.com/IntersectMBO/cardano-ledger/blob/242547effb1eb3e1e710f1565cbb82ff676df3b5/eras/conway/impl/cddl-files/extra.cddl#L3

I'm not knowledgeable enough on how binary format is dealt with on ledger and everything to insist on one thing over another, but having binary tag feels like a sensible update from what I can tell from the comment

**Comment by solidsnakedev** [comment]
This is the workaround we need, but as you said we need to support mainnet as well ,is there a possibility to make this tag serializtion optional, so we can switch on and off between tesnet and mainnet?

```rust
impl<T> From<Vec<T>> for NonemptySet<T> {
    fn from(elems: Vec<T>) -> Self {
        Self {
            elems,
            len_encoding: LenEncoding::default(),
            tag_encoding: Some(Sz::Inline)
        }
    }
}
```

```rust
impl<T: Serialize> Serialize for NonemptySet<T> {
    fn serialize<'se, W: Write>(
        &self,
        serializer: &'se mut Serializer<W>,
        force_canonical: bool,
    ) -> cbor_event::Result<&'se mut Serializer<W>> {
        if let Some(_tag_encoding) = &self.tag_encoding {
            serializer.write_tag(258)?;
        }
        else {
        serializer.write_array_sz(
            self.len_encoding
                .to_len_sz(self.elems.len() as u64, force_canonical),
        )?;
        }
        for elem in self.elems.iter() {
            elem.serialize(serializer, force_canonical)?;
        }
        self.len_encoding.end(serializer, force_canonical)
    }
}
```
This is the result from a TransactionWitnessSet with Vkeywitness

```
a100d90102825820f9aa3fccb7fe539e471188ccc9ee65514c5961c070b06ca185962484a4813bee5840d03dced2ffb4a736df57b834928be81505264cf9561dbc6fec20548883cd70801c37f99aeefba1a06a251077bc8e7f3cbf6afebdda86e0e41b3c38cd95e0bb03
```
Diagnostic notation
```
{
    0: 258_1([
        h'f9aa3fccb7fe539e471188ccc9ee65514c5961c070b06ca185962484a4813bee',
        h'd03dced2ffb4a736df57b834928be81505264cf9561dbc6fec20548883cd70801c37f99aeefba1a06a251077bc8e7f3cbf6afebdda86e0e41b3c38cd95e0bb03',
    ]),
}
```

**Comment by rooooooooob** [comment]
@solidsnakedev  That does not respect the encoding of the tag. Just the first change (but slightly modified) of `tag_encoding: None` -> `tag_encoding: Some(Sz::Two)` (note the `Two` instead of `Inline` as 258 is too big to inline or fit in 1 byte) by itself should, however, work fine and respect it. Doing it this way would require zero changes for mainnet vs testnet, although it would cost a couple lovelace more for transactions compared to before, but it's probably nothing that significant. Each set tag would be an extra 3 bytes.

You don't want to ever use the non-`*_sz` cbor encoding methods (besides `write_special()` since Special tags like Break, True, False, null only have one possible encoding) as if for example someone uses 3 or 4 bytes instead of 2 to encode (which is 100% valid CBOR for 258 set tag) it won't respect it and cause the hashes/etc to not match.

We used to have problems with hashes not matching all the time in CSL so when we made CML we made preserving these CBOR details a priority.

**Comment by solidsnakedev** [comment]
thanks for the feedback @rooooooooob 
@hadelive could you please raise a PR

**Comment by solidsnakedev** [comment]
my bad this serialization should be the correct one.
```rust
impl<T> From<Vec<T>> for NonemptySet<T> {
    fn from(elems: Vec<T>) -> Self {
        Self {
            elems,
            len_encoding: LenEncoding::default(),
            tag_encoding: Some(Sz::Two)
        }
    }
}
```
```rust
impl<T: Serialize> Serialize for NonemptySet<T> {
    fn serialize<'se, W: Write>(
        &self,
        serializer: &'se mut Serializer<W>,
        force_canonical: bool,
    ) -> cbor_event::Result<&'se mut Serializer<W>> {
        if let Some(tag_encoding) = &self.tag_encoding {
        serializer.write_tag_sz(258,*tag_encoding)?;
        }
        serializer.write_array_sz(
            self.len_encoding
                .to_len_sz(self.elems.len() as u64, force_canonical),
        )?;
        for elem in self.elems.iter() {
            elem.serialize(serializer, force_canonical)?;
        }
        self.len_encoding.end(serializer, force_canonical)
    }
}
```
```
a100d9010281825820f9aa3fccb7fe539e471188ccc9ee65514c5961c070b06ca185962484a4813bee58408e782b6a21fbe1361c6220bea7d1327fd8c3d6c1f0d34361193f7a98a5609e6dca08e10c3dc291b746c26018721c786ecc3753c5318458d7da4cc61ef0f97f05
```
now the diagnostic notation looks like this
```
{
    0: 258_1([
        [
            h'f9aa3fccb7fe539e471188ccc9ee65514c5961c070b06ca185962484a4813bee',
            h'8e782b6a21fbe1361c6220bea7d1327fd8c3d6c1f0d34361193f7a98a5609e6dca08e10c3dc291b746c26018721c786ecc3753c5318458d7da4cc61ef0f97f05',
        ],
    ]),
}
```
