### ISSUE TITLE
Improve coin selection

### ISSUE THREAD

**Issue by siegfried** [dcSpark/cardano-multiplatform-lib#62]
According to [this issue](https://github.com/cardano-foundation/CIPs/issues/232), I'm thinking of breaking down current coin selection into these steps:

#### Select Native Assets
1. Regarding the total output amount, sort the UTxOs deterministically. The priority order in the CIP issue does not look good to me. The sets 1/2/3 should be able to be quantified. And the euclidean distance described in[ this issue](https://github.com/Berry-Pool/lucid/issues/17) seems better.
2. Transaction builder takes the first N UTxOs out to satisfy the assets amount needed by outputs. These UTxOs should be fixed.

#### Random Improvement
1. Subtract the total ADA of outputs from total inputs. If the inputs are enough, ignore the following steps.
2. Randomly improves the left ADA with the left UTxOs only holds ADA. If all of the remaining UTxOs contains assets, ignore.
3. Optionally, if random improvement failed, fallback to Largest First.

The sorting and sampling logic can be implemented out of transaction builder, or maybe a separate crate if it can be shared with other projects. Builder can optionally implement a method to take the first N UTxOs to match the native assets of outputs and a method to check if a UTxO can improve. The sorting logic can be implemented by Typescript on the user side as well.

After #57 is merged I can work on this.

**Comment by siegfried** [comment]
Note that the idea is not finalized.

**Comment by siegfried** [comment]
Sometimes I wonder why a random algorithm is needed if there can be a sorting algorithm can work properly. The transaction just need to fetch the UTxOs from the start until the inputs can cover the total output. It is not only easier to implement but also easier to test.

**Comment by siegfried** [comment]
I extract the selection logic which could be used across different UTxO cryptocurrencies into a crate. I just need to implement `Select` trait in this package. https://github.com/siegfried/utxo/blob/master/src/lib.rs
As @rooooooooob said you want to separate the libraries into a pure Rust one and a WASM one, so I think this is the right direction.

**Comment by siegfried** [comment]
Or I could implement the selection in a different package for WASM.

**Comment by siegfried** [comment]
I ended up moving UTxO selection out of `TransactionBuilder`. https://github.com/siegfried/utxo

**Comment by nicolasayotte** [comment]
The simulation plan is to send NFTs and FTs and Ada in an out of a wallet for a large number of transactions -> say 100 000 tx. Those inputs and outputs should be statistically generated to include all kinds of transactions. Then, after 100 000 tx, you measure the state of the wallet by looking into its UTxO distribution.

Do you have super large UTxOs with 20+, or 50+ tokens?
Do you have 1000s of Dust transactions?
Do you have a good balance between large Ada amounts and smaller Ada amounts (to allow for big payment AND independent transactions)?
etc.

**Comment by siegfried** [comment]
> In a nutshell : selecting randomly from those has aggregation properties that will naturally clean up your dust (very small Ada tx). Largest first prevents that random tidying up of small txs.

Then it is no longer necessary because:
1. Dust cannot be produced due to [coinsPerUTxOWord](https://github.com/input-output-hk/cardano-ledger/blob/master/doc/explanations/min-utxo-alonzo.rst);
2. There is no good reason to force the users spending real dust which costs more than its value. Even if there is, those can be added to a result of Largest First algorithm deliberately and optionally.
