### ISSUE TITLE
Change PlutusMap from BtreeMap to Vec

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/cardano-multiplatform-lib#86]
I noticed that Berry's fork of CML changed the PlutusMap to use a Vec instead of a BtreeMap. Not sure what the rationale for this was, but just creating an issue to track this since there may have been a good reason

**Comment by SebastienGllmt** [comment]
So it sounds like it's because when constructing a transaction offchain, PlutusTx maintains insertion order whereas CML isn't because it uses a BtreeMap. Sounds like the solution may be to use a LinkedHashMap? The cddl type does use a map type though and I'm not sure what the implications of the regeneration are on this type

**Comment by rooooooooob** [comment]
This was likely done due to duplicate keys. I'll close this now that we have #241
