### ISSUE TITLE
 Plutus script addresses generated from cborhex by cardano-cli and the serialization lib do not match.

### ISSUE THREAD

**Issue by MIxAxIM** [dcSpark/cardano-multiplatform-lib#89]
Apparently due to a bug or not supporting fee estimation inside cardano serialization library, Addresses generated from Cbor hex of Plutus Script is quit different than actual address that comes from cardano-cli.
It is an open issue on Emergo cardano serialization library for near a year and no fix for it [Issue#233](https://github.com/Emurgo/cardano-serialization-lib/issues/233), But [Alessandro from Nami has a patch for that](https://github.com/alessandrokonrad/cardano-serialization-lib/blob/385faa2babf904f5bbed68e4466f9a1771fac432/rust/src/fees.rs#L30).
I wonder will there be a fix for this problem or is there any other way to produce correct address by DcSpark library?

Below code is an example to reproduce the bug
```javascript
// cborhex of the alwayssucceeds.plutus
const cborhex = "4E4D01000033222220051200120011";
const cbor = Buffer.from(cborhex, "hex");
const blake2bhash = blake.blake2b(cbor, 0, 28); //blake2b-224 -> 28 bytes
const scripthash = ScriptHash.from_bytes(blake2bhash);
const cred = StakeCredential.from_scripthash(scripthash);
const networkId = NetworkInfo.testnet().network_id();
const baseAddr = EnterpriseAddress.new(networkId, cred);
const addr = baseAddr.to_address();
const addrBech32 = addr.to_bech32();

// hash of the address generated from script
console.log(Buffer.from(addr.to_bytes(), "utf8").toString("hex"))

// hash of the address generated using cardano-cli
const ScriptAddress = Address.from_bech32("addr_test1wpnlxv2xv9a9ucvnvzqakwepzl9ltx7jzgm53av2e9ncv4sysemm8");
console.log(Buffer.from(ScriptAddress.to_bytes(), "utf8").toString("hex"))
```
And the hex outputs are:
geneated from cborhex: `70d4e0f6e402a19e086f2fb9914124604ece088db0fa5906fb0f66fc07`
generated by cardano-cli: `7067f33146617a5e61936081db3b2117cbf59bd2123748f58ac9678656`

The corresponding bech32 addresses are:
geneated from cborhex: `addr_test1wpnlxv2xv9a9ucvnvzqakwepzl9ltx7jzgm53av2e9ncv4sysemm8`
generated by cardano-cli: `addr_test1wr2wpahyq2seuzr097uezsfyvp8vuzydkra9jphmpan0cpczfflxx`

The blake package is `npm install blakejs`

**Comment by SebastienGllmt** [comment]
The issue related to the fee that you sent is already addresses in the latest develop branch (just not pushed out to a release). I believe the issue related to the hash should be fixed on latest develop as well (but haven't tested your example)

**Comment by MIxAxIM** [comment]
I tried to use another approach with below code but still I got different hash and address, different even from the example above I gave.
```javascript
const scripthash = PlutusScript.from_bytes(Buffer.from(cborhex, "hex")).hash(ScriptHashNamespace.PlutusV1);
```
So even when latest fix and changes comes which approach should I use to produce correct (same as cardano-cli) address?

**Comment by SebastienGllmt** [comment]
Try with the latest version

```
const scripthash = PlutusV1Script.from_bytes(Buffer.from("4e4d01000033222220051200120011", "hex")).hash()
```

And make sure your script is a V1 script. This should give the same as what cardano-cli gives you

**Comment by MIxAxIM** [comment]
Thank you [Sebastien](https://github.com/SebastienGllmt) and dcSpark team for your hard works, this issues finally has been solved.
