### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by khoanguyen-yang** [dcSpark/cardano-multiplatform-lib#91]
Trying using the existing packages with React Native and got these errors:

`...@dcspark/cardano-multiplatform-lib-browser/package.json was successfully found. However, this package itself specifies a mainmodule field that could not be resolved`
`...@dcspark/cardano-multiplatform-lib-asmjs/package.json was successfully found. However, this package itself specifies a main module field that could not be resolved`

Is there any support for React Native in the roadmap?

Many thanks

**Comment by nicarq** [comment]
Currently React Native support is not in the roadmap. There is another library for React Native https://github.com/Emurgo/react-native-haskell-shelley you could also modify it to use CML rather than CSL if CSL doesn't work for you
